# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/test_thing',
                'doc_host': 'https://yannsay.github.io',
                'git_url': 'https://github.com/yannsay/test_thing',
                'lib_path': 'test_thing'},
  'syms': { 'test_thing.components.module1': { 'test_thing.components.module1.papaya': ( 'components/module1.html#papaya',
                                                                                         'test_thing/components/module1.py')},
            'test_thing.core': {'test_thing.core.foo': ('core.html#foo', 'test_thing/core.py')},
            'test_thing.main': {'test_thing.main.home': ('main.html#home', 'test_thing/main.py')}}}
