"""File to launch the app"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_main.ipynb.

# %% auto 0
__all__ = ['app', 'home']

# %% ../nbs/01_main.ipynb 3
from fasthtml.common import FastHTML, serve

app = FastHTML()

@app.get("/")
def home():
    return f"<h1>Hello, World ! {papaya()}</h1>"


# %% ../nbs/01_main.ipynb 4
import sys

# %% ../nbs/01_main.ipynb 6
sys.path.append(".")


# %% ../nbs/01_main.ipynb 8
from components.module1 import *
