"""This is a module in a folder"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/module1.ipynb.

# %% auto 0
__all__ = ['papaya']

# %% ../../nbs/components/module1.ipynb 3
def papaya(): return "papaya"
